export const creators = [
  {
    id: "c1",
    name: "Mara Chen",
    handle: "marachen",
    initials: "MC",
    verified: true,
    bio: "Conversion strategist turning customer research into useful AI systems.",
    products: 6,
    followers: 12800,
  },
  {
    id: "c2",
    name: "Ellis North",
    handle: "ellisnorth",
    initials: "EN",
    verified: true,
    bio: "Developer experience engineer and open-source maintainer.",
    products: 9,
    followers: 8400,
  },
  {
    id: "c3",
    name: "Dr. Amara Okafor",
    handle: "amara-research",
    initials: "AO",
    verified: true,
    bio: "Clinical evidence researcher building careful research workflows.",
    products: 4,
    followers: 6200,
  },
  {
    id: "c4",
    name: "Jon Bell",
    handle: "jonbuilds",
    initials: "JB",
    verified: false,
    bio: "Independent product builder focused on practical automation.",
    products: 3,
    followers: 2100,
  },
  {
    id: "c5",
    name: "Studio Common",
    handle: "studiocommon",
    initials: "SC",
    verified: true,
    bio: "A small brand systems practice for teams with big ambitions.",
    products: 7,
    followers: 9700,
  },
];
const [mara, ellis, amara, jon, studio] = creators;
const products = [
  {
    id: "p1",
    slug: "conversion-copywriter",
    name: "Conversion Copywriter",
    type: "Skill",
    outcome:
      "Turn raw customer insight into credible, conversion-focused copy.",
    description:
      "A structured writing skill that researches the offer, identifies the strongest argument, and drafts landing pages without empty hype.",
    creator: mara,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT", "Codex"],
      models: ["Claude 4", "GPT-5"],
    },
    category: "Marketing",
    rating: 4.9,
    reviewCount: 184,
    usageCount: 3200,
    updatedAt: "Aug 18, 2026",
    version: "2.4.0",
    featured: true,
    verified: true,
    tags: ["copywriting", "research", "landing pages"],
  },
  {
    id: "p2",
    slug: "pull-request-guardian",
    name: "Pull Request Guardian",
    type: "Agent",
    outcome: "Review pull requests for regressions, risk, and missing tests.",
    description: "An opinionated code-review agent for engineering teams.",
    creator: ellis,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Codex", "Cursor", "VS Code"],
      models: ["GPT-5", "Claude 4"],
    },
    category: "Development",
    rating: 4.8,
    reviewCount: 96,
    usageCount: 1800,
    updatedAt: "Aug 22, 2026",
    version: "1.8.2",
    trending: true,
    verified: true,
    tags: ["code review", "testing"],
  },
  {
    id: "p3",
    slug: "clinical-literature-scout",
    name: "Clinical Literature Scout",
    type: "Workflow",
    outcome:
      "Find, screen, and synthesize clinical evidence with citations intact.",
    description:
      "A reproducible evidence-search workflow with quality guardrails.",
    creator: amara,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT"],
      models: ["Claude 4", "GPT-5"],
    },
    category: "Research",
    rating: 4.9,
    reviewCount: 72,
    usageCount: 940,
    updatedAt: "Aug 9, 2026",
    version: "3.1.0",
    featured: true,
    verified: true,
    tags: ["clinical", "citations"],
  },
  {
    id: "p4",
    slug: "brand-voice-architect",
    name: "Brand Voice Architect",
    type: "Prompt pack",
    outcome: "Build a distinctive, repeatable voice from real writing samples.",
    description:
      "Interview prompts, analysis rubrics, and production templates.",
    creator: studio,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT", "Gemini"],
      models: ["Model agnostic"],
    },
    category: "Marketing",
    rating: 4.7,
    reviewCount: 131,
    usageCount: 2700,
    updatedAt: "Jul 30, 2026",
    version: "2.0",
    verified: true,
    tags: ["brand", "voice"],
  },
  {
    id: "p5",
    slug: "support-inbox-triage",
    name: "Support Inbox Triage",
    type: "Agent",
    outcome:
      "Classify, prioritize, and draft replies for customer support queues.",
    description: "A configurable support operations agent.",
    creator: jon,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: { platforms: ["ChatGPT", "API"], models: ["GPT-5"] },
    category: "Operations",
    rating: 4.5,
    reviewCount: 48,
    usageCount: 760,
    updatedAt: "Aug 2, 2026",
    version: "1.4",
    verified: false,
    tags: ["support", "operations"],
  },
  {
    id: "p6",
    slug: "financial-model-reviewer",
    name: "Financial Model Reviewer",
    type: "Skill",
    outcome:
      "Spot assumption gaps and formula risks before stakeholder review.",
    description: "A skeptical second pass for forecasts and operating models.",
    creator: amara,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT"],
      models: ["Claude 4", "GPT-5"],
    },
    category: "Finance",
    rating: 4.8,
    reviewCount: 63,
    usageCount: 1100,
    updatedAt: "Aug 14, 2026",
    version: "1.9",
    verified: true,
    tags: ["finance", "models"],
  },
  {
    id: "p7",
    slug: "next-accessibility-auditor",
    name: "Next.js Accessibility Auditor",
    type: "Developer utility",
    outcome: "Audit routes and components for practical WCAG failures.",
    description:
      "Checks semantics, focus paths, labels, and common App Router issues.",
    creator: ellis,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Codex", "Cursor", "VS Code"],
      models: ["Model agnostic"],
    },
    category: "Development",
    rating: 4.8,
    reviewCount: 210,
    usageCount: 8900,
    updatedAt: "Aug 24, 2026",
    version: "4.0",
    trending: true,
    verified: true,
    tags: ["a11y", "Next.js"],
  },
  {
    id: "p8",
    slug: "research-brief-generator",
    name: "Research Brief Generator",
    type: "Prompt",
    outcome:
      "Turn an ambiguous question into a rigorous, scoped research plan.",
    description:
      "A careful prompt for better research questions and source criteria.",
    creator: amara,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT", "Gemini"],
      models: ["Model agnostic"],
    },
    category: "Research",
    rating: 4.6,
    reviewCount: 88,
    usageCount: 2400,
    updatedAt: "Jul 18, 2026",
    version: "1.2",
    verified: true,
    tags: ["research", "planning"],
  },
  {
    id: "p9",
    slug: "mcp-database-explorer",
    name: "MCP Database Explorer",
    type: "MCP server",
    outcome: "Let agents inspect schemas and run governed read-only queries.",
    description:
      "A documented MCP server with permission controls and audit logs.",
    creator: ellis,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "Codex", "VS Code"],
      models: ["Model agnostic"],
    },
    category: "Development",
    rating: 4.9,
    reviewCount: 54,
    usageCount: 680,
    updatedAt: "Aug 25, 2026",
    version: "2.2.1",
    featured: true,
    verified: true,
    tags: ["MCP", "database"],
  },
  {
    id: "p10",
    slug: "product-strategy-partner",
    name: "Product Strategy Partner",
    type: "Skill",
    outcome:
      "Pressure-test product decisions with evidence and explicit tradeoffs.",
    description:
      "A strategy skill for framing bets, assumptions, and decision criteria.",
    creator: jon,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["Claude", "ChatGPT"],
      models: ["Claude 4", "GPT-5"],
    },
    category: "Product",
    rating: 4.6,
    reviewCount: 77,
    usageCount: 1500,
    updatedAt: "Aug 6, 2026",
    version: "1.6",
    verified: false,
    tags: ["strategy", "decisions"],
  },
  {
    id: "p11",
    slug: "meeting-decision-extractor",
    name: "Meeting Decision Extractor",
    type: "Workflow",
    outcome:
      "Extract decisions, owners, and unresolved questions from transcripts.",
    description:
      "A concise post-meeting workflow that separates commitments from discussion.",
    creator: studio,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["ChatGPT", "Claude", "Gemini"],
      models: ["Model agnostic"],
    },
    category: "Productivity",
    rating: 4.7,
    reviewCount: 302,
    usageCount: 12000,
    updatedAt: "Aug 12, 2026",
    version: "3.0",
    trending: true,
    verified: true,
    tags: ["meetings", "decisions"],
  },
  {
    id: "p12",
    slug: "image-prompt-director",
    name: "Image Prompt Director",
    type: "Prompt pack",
    outcome: "Direct coherent campaign imagery across multiple image models.",
    description:
      "Art-direction frameworks for composition, lighting, and continuity.",
    creator: studio,
    pricing: { amount: 0, currency: "USD", model: "free" },
    compatibility: {
      platforms: ["ChatGPT", "Gemini"],
      models: ["Model agnostic"],
    },
    category: "Creative",
    rating: 4.7,
    reviewCount: 119,
    usageCount: 2100,
    updatedAt: "Jul 27, 2026",
    version: "2.3",
    verified: true,
    tags: ["image", "art direction"],
  },
];
export { products };
export const reviews = [
  {
    id: "r1",
    author: "Priya S.",
    rating: 5,
    date: "Aug 20, 2026",
    body: "The first copy system I have used that asks for evidence before adjectives. The messaging hierarchy alone was worth it.",
    verifiedPurchase: true,
  },
  {
    id: "r2",
    author: "Alex Moreno",
    rating: 5,
    date: "Aug 11, 2026",
    body: "Clear files, thoughtful examples, and a changelog that explains why each update matters.",
    verifiedPurchase: true,
  },
  {
    id: "r3",
    author: "Noah Kim",
    rating: 4,
    date: "Jul 28, 2026",
    body: "Strong for landing pages. I would like more SaaS onboarding examples in the next version.",
    verifiedPurchase: true,
  },
];
export const versions = [
  {
    version: "2.4.0",
    date: "Aug 18, 2026",
    notes: "Added objection-mining workflow and GPT-5 compatibility notes.",
  },
  {
    version: "2.3.1",
    date: "Jul 24, 2026",
    notes: "Improved evidence checks and clarified voice constraints.",
  },
  {
    version: "2.0.0",
    date: "May 7, 2026",
    notes: "Rebuilt the skill around a research-first messaging framework.",
  },
];
export const categories = [
  "All",
  "Development",
  "Marketing",
  "Research",
  "Operations",
  "Finance",
  "Product",
  "Productivity",
  "Creative",
];
