import type { Creator, Product, ProductDetail } from "./types";
export const creators: Creator[] = [
  { id: "fixture-creator-1", name: "Mara Chen", handle: "marachen", initials: "MC", verified: true, bio: "Conversion strategist turning customer research into useful AI systems.", products: 6, followers: 12800 },
  { id: "fixture-creator-2", name: "Ellis North", handle: "ellisnorth", initials: "EN", verified: true, bio: "Developer experience engineer and open-source maintainer.", products: 9, followers: 8400 },
  { id: "fixture-creator-3", name: "Amara Okafor", handle: "amara", initials: "AO", verified: true, bio: "Evidence researcher building careful workflows.", products: 4, followers: 6200 },
  { id: "fixture-creator-4", name: "Jon Bell", handle: "jonbuilds", initials: "JB", verified: false, bio: "Independent product builder.", products: 3, followers: 2100 },
];
const base: Product = { id: "fixture-product", slug: "conversion-copywriter", name: "Conversion Copywriter", type: "Skill", typeKey: "skill", outcome: "Turn raw customer insight into credible copy.", description: "A research-first writing system.", creator: creators[0], pricing: { amountMinor: 0, currency: "USD", model: "free" }, compatibility: { platforms: ["Claude", "ChatGPT", "Codex"], models: ["Claude 4", "GPT-5"] }, category: "Marketing", rating: 4.9, reviewCount: 184, usageCount: 3200, purchaseCount: 3200, updatedAt: "2026-08-18T00:00:00.000Z", version: "2.4.0", featured: true, verified: true, tags: ["copywriting", "research"], communities: [] };
export const products: Product[] = Array.from({ length: 10 }, (_, index) => ({ ...base, id: `fixture-product-${index}`, slug: index ? `fixture-product-${index}` : base.slug, name: index ? `Resource ${index + 1}` : base.name, creator: creators[index % creators.length], verified: index !== 9 }));
export const productDetail: ProductDetail = { ...products[0], packageFileCount: 2, packageSizeBytes: 1024, benefits: [], useCases: [], includedFiles: [], exampleInput: null, exampleOutputTitle: null, exampleOutputBody: null, previewFiles: ["README.md"], previewExcerpt: "# Preview", requirements: null, permissions: null, license: "MIT", updatesPolicy: null, refundPolicy: null, versions: [], reviews: [], related: [] };
