export type Locale = "en" | "fa";

export function localePath(path: string, locale: Locale): string {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return locale === "fa" ? `/fa${normalized === "/" ? "" : normalized}` : normalized;
}

export const footerLabels = {
  en: {
    marketplace: "Marketplace", explore: "Explore", collections: "Collections", newReleases: "New releases",
    create: "Create", creatorGuide: "Creator guide", qualityStandards: "Quality standards",
    company: "Company", about: "About", journal: "Journal", support: "Support", permissions: "Permissions on every listing",
  },
  fa: {
    marketplace: "بازارچه", explore: "کاوش", collections: "مجموعه‌ها", newReleases: "انتشارهای تازه",
    create: "ساختن", creatorGuide: "راهنمای سازندگان", qualityStandards: "استانداردهای کیفیت",
    company: "شرکت", about: "درباره", journal: "مجله", support: "پشتیبانی", permissions: "مجوزها در هر فهرست",
  },
} as const;

export const copy = {
  en: {
    language: "فارسی", explore: "Explore", designSystem: "Design system", signIn: "Sign in", close: "Close menu", open: "Open menu", primary: "Primary", mobile: "Mobile", announcement: "New: verified MCP servers with transparent permission reviews", marketplace: "The marketplace for AI building blocks", heroStop: "Stop prompting", heroScratch: "from scratch.", heroStart: "Start from what works.", heroIntro: "Prompts, skills, agents and MCP servers built by people who already got the model to behave — each one listed with its permissions, compatibility and safety review in plain sight.", exploreMarketplace: "Explore the marketplace", sellWork: "Sell your work", declared: "Every listing declares what it touches before you install it.", worksWith: "Works with", featuredEyebrow: "Chosen with care", featuredTitle: "Featured building blocks", viewAll: "View all {count} listings", unavailable: "Marketplace data is temporarily unavailable. Please try again shortly.", trustEyebrow: "Trust is product information.", collectionsEyebrow: "Curated collections", practiceEyebrow: "Browse by practice", creatorsEyebrow: "People worth following", featuredCreators: "Featured creators", inboxEyebrow: "A quieter, better inbox", inboxTitle: "One useful release every Friday.", account: "Your account", signedInAs: "Signed in as", signOut: "Sign out", accountIntro: "Use one account for the TermSpace marketplace and editorial library.", createAccount: "Create account", needAccount: "Need an account? Register", registered: "Already registered? Sign in", email: "Email", password: "Password", wait: "Please wait…", serviceError: "Account services are temporarily unavailable.", home: "Home", footer: "The marketplace for AI building blocks. Carefully made, clearly explained.", discovery: { marketplace: "Marketplace", title: "Find your next advantage.", intro: "Search trustworthy, reusable products made to improve real AI work.", search: "Search by product, outcome, or creator…", productType: "Product type", all: "All", category: "Category", compatibility: "Compatibility", pricing: "Pricing", rating: "Rating", anyRating: "Any", verifiedOnly: "Verified only", filters: "Filters", showResults: "Show {count} results", sort: "Sort products", featured: "Featured", topRated: "Top rated", recentlyUpdated: "Recently updated", priceLow: "Price: low to high", gridView: "Grid view", listView: "List view", clearAll: "Clear all", products: "products", loadMore: "Load more products", loading: "Loading…", retry: "Retry", rateLimited: "The marketplace is rate-limited. Please wait a moment and try again.", connectionError: "Could not reach the marketplace. Check your connection and try again." } },
  fa: {
    language: "English", explore: "کاوش", designSystem: "سیستم طراحی", signIn: "ورود", close: "بستن منو", open: "باز کردن منو", primary: "اصلی", mobile: "موبایل", announcement: "تازه: سرورهای MCP تأییدشده با بررسی شفاف مجوزها", marketplace: "بازارچهٔ اجزای سازندهٔ هوش مصنوعی", heroStop: "از درخواست‌های تکراری", heroScratch: "از صفر دست بکشید.", heroStart: "از چیزی که کار می‌کند شروع کنید.", heroIntro: "پرامپت‌ها، مهارت‌ها، عامل‌ها و سرورهای MCP را افرادی ساخته‌اند که مدل را به کار گرفته‌اند؛ هر مورد با مجوزها، سازگاری و بررسی ایمنی شفاف معرفی می‌شود.", exploreMarketplace: "کاوش در بازارچه", sellWork: "فروش کار شما", declared: "هر فهرست پیش از نصب مشخص می‌کند با چه چیزهایی تعامل دارد.", worksWith: "سازگار با", featuredEyebrow: "با دقت انتخاب‌شده", featuredTitle: "اجزای منتخب", viewAll: "مشاهدهٔ {count} فهرست", unavailable: "داده‌های بازارچه موقتاً در دسترس نیست. لطفاً کمی بعد دوباره تلاش کنید.", trustEyebrow: "اعتماد، بخشی از اطلاعات محصول است.", collectionsEyebrow: "مجموعه‌های گزینش‌شده", practiceEyebrow: "بر اساس شیوهٔ کار کاوش کنید", creatorsEyebrow: "افرادی که ارزش دنبال‌کردن دارند", featuredCreators: "سازندگان منتخب", inboxEyebrow: "صندوق ورودی آرام‌تر و مفیدتر", inboxTitle: "هر جمعه یک انتشار مفید.", account: "حساب شما", signedInAs: "واردشده با", signOut: "خروج", accountIntro: "با یک حساب به بازارچهٔ ترم‌اسپیس و کتابخانهٔ تحریریه دسترسی داشته باشید.", createAccount: "ساخت حساب", needAccount: "حساب ندارید؟ ثبت‌نام کنید", registered: "قبلاً ثبت‌نام کرده‌اید؟ وارد شوید", email: "ایمیل", password: "رمز عبور", wait: "لطفاً صبر کنید…", serviceError: "خدمات حساب موقتاً در دسترس نیست.", home: "خانه", footer: "بازارچهٔ اجزای هوش مصنوعی؛ با دقت ساخته‌شده و شفاف توضیح‌داده‌شده.", discovery: { marketplace: "بازارچه", title: "مزیت بعدی خود را پیدا کنید.", intro: "محصولات قابل اعتماد و قابل استفادهٔ مجدد را برای بهبود کار واقعی با هوش مصنوعی جست‌وجو کنید.", search: "بر اساس محصول، نتیجه یا سازنده جست‌وجو کنید…", productType: "نوع محصول", all: "همه", category: "دسته‌بندی", compatibility: "سازگاری", pricing: "قیمت‌گذاری", rating: "امتیاز", anyRating: "هر امتیازی", verifiedOnly: "فقط تأییدشده", filters: "فیلترها", showResults: "نمایش {count} نتیجه", sort: "مرتب‌سازی محصولات", featured: "منتخب", topRated: "بالاترین امتیاز", recentlyUpdated: "به‌روزرسانی اخیر", priceLow: "قیمت: کم به زیاد", gridView: "نمای شبکه‌ای", listView: "نمای فهرستی", clearAll: "پاک‌کردن همه", products: "محصول", loadMore: "بارگذاری محصولات بیشتر", loading: "در حال بارگذاری…", retry: "تلاش دوباره", rateLimited: "درخواست‌های بازارچه موقتاً محدود شده است. کمی صبر کنید و دوباره تلاش کنید.", connectionError: "ارتباط با بازارچه برقرار نشد. اتصال خود را بررسی و دوباره تلاش کنید." } },
} as const;
