FROM node:22-bookworm-slim AS build

WORKDIR /app
ARG API_URL=http://localhost:4001
ARG NEXT_PUBLIC_BLOG_URL=http://localhost:3001
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_BLOG_URL=$NEXT_PUBLIC_BLOG_URL
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/blog/package.json apps/blog/package.json
COPY apps/web/package.json apps/web/package.json
RUN npm ci
COPY apps/web apps/web
ARG API_URL=http://localhost:4001
ARG NEXT_PUBLIC_BLOG_URL=http://localhost:3001
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_BLOG_URL=$NEXT_PUBLIC_BLOG_URL
RUN npm run build --workspace @termspace/web

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/web/package.json apps/web/package.json
COPY --from=build /app/apps/web/.next apps/web/.next
COPY --from=build /app/apps/web/public apps/web/public
RUN chown -R node:node /app

EXPOSE 3000
USER node
CMD ["npm", "run", "start", "--workspace", "@termspace/web"]
