import { Router } from "express";
import { acquireMarketplaceProduct, addMarketplaceFavorite, getMarketplaceCommunity, getMarketplaceHome, getMarketplaceInstallation, getMarketplaceProduct, listMarketplaceCommunities, listMarketplaceFavorites, listMarketplaceItemTypes, listMarketplaceLibrary, listMarketplaceProducts, removeMarketplaceFavorite } from "../controllers/marketplaceController.js";
import { createOwnedCreatorProfile, getCreatorDashboard, getOwnedCreatorProfile, listOwnedMarketplaceReleases, updateOwnedCreatorProfile } from "../controllers/marketplaceCreatorController.js";
import { transitionModeratedMarketplaceListing, transitionOwnedMarketplaceListing } from "../controllers/marketplaceLifecycleController.js";
import { createOwnedMarketplaceDraft, getOwnedMarketplaceDraft, listMarketplaceDraftOptions, updateOwnedMarketplaceDraft } from "../controllers/marketplaceDraftController.js";
import { addMarketplaceModerationNote, getMarketplaceModerationPreview, listMarketplaceModerationQueue, moderateMarketplaceCommunityPlacement } from "../controllers/marketplaceModerationController.js";
import { connectOwnedProvider, enqueueOwnedSourceCheck, listOwnedProviderConnections, revokeOwnedProvider } from "../controllers/marketplaceSourceController.js";
import { requireMarketplaceRole, requireReader, requireVerifiedReader } from "../middleware/auth.js";
import { validate, validateRouteParam } from "../middleware/validate.js";
import { communityPlacementDecisionSchema, creatorDashboardQuerySchema, creatorDraftCreateSchema, creatorDraftUpdateSchema, creatorListingLifecycleSchema, creatorOnboardingSchema, creatorProfileUpdateSchema, marketplaceLibraryQuerySchema, marketplaceProductQuerySchema, marketplaceProviderSchema, moderatedListingLifecycleSchema, moderationNoteSchema, moderationQueueQuerySchema, providerConnectionSchema, routeIdSchema, routeSlugSchema, sourceCheckRequestSchema } from "../validation/schemas.js";

const router = Router();
router.param("id", validateRouteParam("id", routeIdSchema));
router.param("slug", validateRouteParam("slug", routeSlugSchema));
router.param("provider", validateRouteParam("provider", marketplaceProviderSchema));
router.param("communitySlug", validateRouteParam("communitySlug", routeSlugSchema));
router.get("/home", getMarketplaceHome);
router.get("/item-types", listMarketplaceItemTypes);
router.get("/communities", listMarketplaceCommunities);
router.get("/communities/:slug", validate(marketplaceProductQuerySchema, "query"), getMarketplaceCommunity);
router.get("/draft-options", listMarketplaceDraftOptions);
router.get("/products", validate(marketplaceProductQuerySchema, "query"), listMarketplaceProducts);
router.get("/products/:slug", getMarketplaceProduct);
router.get("/creator/profile", requireReader, getOwnedCreatorProfile);
router.post("/creator/profile", requireReader, requireVerifiedReader, validate(creatorOnboardingSchema), createOwnedCreatorProfile);
router.patch("/creator/profile", requireMarketplaceRole("creator"), validate(creatorProfileUpdateSchema), updateOwnedCreatorProfile);
router.get("/creator/dashboard", requireMarketplaceRole("creator"), validate(creatorDashboardQuerySchema, "query"), getCreatorDashboard);
router.get("/creator/provider-connections", requireMarketplaceRole("creator"), listOwnedProviderConnections);
router.put("/creator/provider-connections/:provider", requireMarketplaceRole("creator"), validate(providerConnectionSchema), connectOwnedProvider);
router.delete("/creator/provider-connections/:provider", requireMarketplaceRole("creator"), revokeOwnedProvider);
router.post("/creator/products", requireMarketplaceRole("creator"), validate(creatorDraftCreateSchema), createOwnedMarketplaceDraft);
router.get("/creator/products/:id/draft", requireMarketplaceRole("creator"), getOwnedMarketplaceDraft);
router.get("/creator/products/:id/releases", requireMarketplaceRole("creator"), listOwnedMarketplaceReleases);
router.post("/creator/products/:id/source-check", requireMarketplaceRole("creator"), validate(sourceCheckRequestSchema), enqueueOwnedSourceCheck);
router.put("/creator/products/:id/draft", requireMarketplaceRole("creator"), validate(creatorDraftUpdateSchema), updateOwnedMarketplaceDraft);
router.post("/creator/products/:id/lifecycle", requireMarketplaceRole("creator"), validate(creatorListingLifecycleSchema), transitionOwnedMarketplaceListing);
router.get("/moderation/queue", requireMarketplaceRole("moderator", "administrator"), validate(moderationQueueQuerySchema, "query"), listMarketplaceModerationQueue);
router.get("/moderation/products/:id", requireMarketplaceRole("moderator", "administrator"), getMarketplaceModerationPreview);
router.post("/moderation/products/:id/notes", requireMarketplaceRole("moderator", "administrator"), validate(moderationNoteSchema), addMarketplaceModerationNote);
router.post("/moderation/products/:id/community-placements/:communitySlug", requireMarketplaceRole("moderator", "administrator"), validate(communityPlacementDecisionSchema), moderateMarketplaceCommunityPlacement);
router.post("/moderation/products/:id/lifecycle", requireMarketplaceRole("moderator", "administrator"), validate(moderatedListingLifecycleSchema), transitionModeratedMarketplaceListing);
router.get("/favorites", requireReader, listMarketplaceFavorites);
router.get("/library", requireReader, validate(marketplaceLibraryQuerySchema, "query"), listMarketplaceLibrary);
router.put("/products/:slug/favorite", requireReader, addMarketplaceFavorite);
router.delete("/products/:slug/favorite", requireReader, removeMarketplaceFavorite);
router.get("/products/:slug/installation", requireReader, getMarketplaceInstallation);
router.post("/products/:slug/acquire", requireReader, acquireMarketplaceProduct);
export default router;
