import { Router } from "express";
import { acquireMarketplaceProduct, addMarketplaceFavorite, getMarketplaceHome, getMarketplaceProduct, listMarketplaceFavorites, listMarketplaceItemTypes, listMarketplaceProducts, removeMarketplaceFavorite } from "../controllers/marketplaceController.js";
import { createOwnedCreatorProfile, getCreatorDashboard, getOwnedCreatorProfile, listOwnedMarketplaceReleases, updateOwnedCreatorProfile } from "../controllers/marketplaceCreatorController.js";
import { transitionModeratedMarketplaceListing, transitionOwnedMarketplaceListing } from "../controllers/marketplaceLifecycleController.js";
import { createOwnedMarketplaceDraft, getOwnedMarketplaceDraft, listMarketplaceDraftOptions, updateOwnedMarketplaceDraft } from "../controllers/marketplaceDraftController.js";
import { addMarketplaceModerationNote, getMarketplaceModerationPreview, listMarketplaceModerationQueue } from "../controllers/marketplaceModerationController.js";
import { requireMarketplaceRole, requireReader, requireVerifiedReader } from "../middleware/auth.js";
import { validate, validateRouteParam } from "../middleware/validate.js";
import { creatorDashboardQuerySchema, creatorDraftCreateSchema, creatorDraftUpdateSchema, creatorListingLifecycleSchema, creatorOnboardingSchema, creatorProfileUpdateSchema, marketplaceProductQuerySchema, moderatedListingLifecycleSchema, moderationNoteSchema, moderationQueueQuerySchema, routeIdSchema, routeSlugSchema } from "../validation/schemas.js";

const router = Router();
router.param("id", validateRouteParam("id", routeIdSchema));
router.param("slug", validateRouteParam("slug", routeSlugSchema));
router.get("/home", getMarketplaceHome);
router.get("/item-types", listMarketplaceItemTypes);
router.get("/draft-options", listMarketplaceDraftOptions);
router.get("/products", validate(marketplaceProductQuerySchema, "query"), listMarketplaceProducts);
router.get("/products/:slug", getMarketplaceProduct);
router.get("/creator/profile", requireReader, getOwnedCreatorProfile);
router.post("/creator/profile", requireReader, requireVerifiedReader, validate(creatorOnboardingSchema), createOwnedCreatorProfile);
router.patch("/creator/profile", requireMarketplaceRole("creator"), validate(creatorProfileUpdateSchema), updateOwnedCreatorProfile);
router.get("/creator/dashboard", requireMarketplaceRole("creator"), validate(creatorDashboardQuerySchema, "query"), getCreatorDashboard);
router.post("/creator/products", requireMarketplaceRole("creator"), validate(creatorDraftCreateSchema), createOwnedMarketplaceDraft);
router.get("/creator/products/:id/draft", requireMarketplaceRole("creator"), getOwnedMarketplaceDraft);
router.get("/creator/products/:id/releases", requireMarketplaceRole("creator"), listOwnedMarketplaceReleases);
router.put("/creator/products/:id/draft", requireMarketplaceRole("creator"), validate(creatorDraftUpdateSchema), updateOwnedMarketplaceDraft);
router.post("/creator/products/:id/lifecycle", requireMarketplaceRole("creator"), validate(creatorListingLifecycleSchema), transitionOwnedMarketplaceListing);
router.get("/moderation/queue", requireMarketplaceRole("moderator", "administrator"), validate(moderationQueueQuerySchema, "query"), listMarketplaceModerationQueue);
router.get("/moderation/products/:id", requireMarketplaceRole("moderator", "administrator"), getMarketplaceModerationPreview);
router.post("/moderation/products/:id/notes", requireMarketplaceRole("moderator", "administrator"), validate(moderationNoteSchema), addMarketplaceModerationNote);
router.post("/moderation/products/:id/lifecycle", requireMarketplaceRole("moderator", "administrator"), validate(moderatedListingLifecycleSchema), transitionModeratedMarketplaceListing);
router.get("/favorites", requireReader, listMarketplaceFavorites);
router.put("/products/:slug/favorite", requireReader, addMarketplaceFavorite);
router.delete("/products/:slug/favorite", requireReader, removeMarketplaceFavorite);
router.post("/products/:slug/acquire", requireReader, acquireMarketplaceProduct);
export default router;
