import { Router } from "express";
import { rateLimit } from "express-rate-limit";
import { getDiscoveryOptions, getPublicCommunity, getPublicCreator, getPublicCollection, listCommunityPlacements, decideCommunityPlacement, listOwnedCollections, saveOwnedCollection, listManagedCommunities, saveManagedCommunity } from "../controllers/marketplaceCommunityController.js";
import { createAccountCase, reportMarketplaceTarget, listMarketplaceCases, decideMarketplaceCase, appealMarketplaceCase, decideMarketplaceAppeal } from "../controllers/marketplaceTrustController.js";
import { accountCaseSchema, communitySchema, placementDecisionSchema, collectionSchema, reportSchema, caseDecisionSchema, appealSchema, appealDecisionSchema } from "../validation/marketplaceCommunitySchemas.js";
import { acquireMarketplaceProduct, addMarketplaceFavorite, getMarketplaceHome, getMarketplaceInstallation, getMarketplaceProduct, listMarketplaceFavorites, listMarketplaceItemTypes, listMarketplaceLibrary, listMarketplaceProducts, removeMarketplaceFavorite } from "../controllers/marketplaceController.js";
import { createOwnedCreatorProfile, getCreatorDashboard, getOwnedCreatorProfile, listOwnedMarketplaceReleases, updateOwnedCreatorProfile } from "../controllers/marketplaceCreatorController.js";
import { transitionModeratedMarketplaceListing, transitionOwnedMarketplaceListing } from "../controllers/marketplaceLifecycleController.js";
import { createOwnedMarketplaceDraft, getOwnedMarketplaceDraft, listMarketplaceDraftOptions, updateOwnedMarketplaceDraft } from "../controllers/marketplaceDraftController.js";
import { addMarketplaceModerationNote, getMarketplaceModerationPreview, listMarketplaceModerationQueue } from "../controllers/marketplaceModerationController.js";
import { connectOwnedProvider, enqueueOwnedSourceCheck, listOwnedProviderConnections, revokeOwnedProvider } from "../controllers/marketplaceSourceController.js";
import { requireMarketplaceRole, requireMarketplaceAccess, requireReader, requireVerifiedReader } from "../middleware/auth.js";
import { validate, validateRouteParam } from "../middleware/validate.js";
import { creatorDashboardQuerySchema, creatorDraftCreateSchema, creatorDraftUpdateSchema, creatorListingLifecycleSchema, creatorOnboardingSchema, creatorProfileUpdateSchema, marketplaceLibraryQuerySchema, marketplaceProductQuerySchema, marketplaceProviderSchema, moderatedListingLifecycleSchema, moderationNoteSchema, moderationQueueQuerySchema, providerConnectionSchema, routeIdSchema, routeSlugSchema, sourceCheckRequestSchema } from "../validation/schemas.js";

const router = Router();
const reportLimit = rateLimit({ windowMs: 60 * 60 * 1000, limit: 8, keyGenerator: (_req, res) => res.locals.reader.id, standardHeaders: "draft-8", legacyHeaders: false, message: { error: { code: "RATE_LIMITED", message: "Report limit reached; try again later" } } });
const submissionLimit = rateLimit({ windowMs: 60 * 60 * 1000, limit: 12, keyGenerator: (_req, res) => res.locals.reader.id, standardHeaders: "draft-8", legacyHeaders: false, message: { error: { code: "RATE_LIMITED", message: "Submission limit reached; try again later" } } });
router.param("id", validateRouteParam("id", routeIdSchema));
router.param("slug", validateRouteParam("slug", routeSlugSchema));
router.param("handle", validateRouteParam("handle", routeSlugSchema));
router.param("provider", validateRouteParam("provider", marketplaceProviderSchema));
router.get("/home", getMarketplaceHome);
router.get("/discovery-options", getDiscoveryOptions);
router.get("/communities/:slug", getPublicCommunity);
router.get("/creators/:handle", getPublicCreator);
router.get("/creators/:handle/collections/:slug", getPublicCollection);
router.get("/creator/collections", requireMarketplaceRole("creator"), listOwnedCollections);
router.put("/creator/collections/:slug", requireMarketplaceRole("creator"), validate(collectionSchema), saveOwnedCollection);
router.get("/creator/placements", requireMarketplaceRole("creator"), validate(creatorDashboardQuerySchema, "query"), listCommunityPlacements);
router.get("/cases", requireReader, validate(creatorDashboardQuerySchema, "query"), listMarketplaceCases);
router.post("/cases/:id/appeals", requireReader, validate(appealSchema), appealMarketplaceCase);
router.post("/reports", requireReader, requireMarketplaceAccess, reportLimit, validate(reportSchema), reportMarketplaceTarget);
router.get("/moderation/communities", requireMarketplaceRole("administrator"), listManagedCommunities);
router.put("/moderation/communities/:slug", requireMarketplaceRole("administrator"), validate(communitySchema), saveManagedCommunity);
router.get("/moderation/placements", requireMarketplaceRole("moderator", "administrator"), validate(creatorDashboardQuerySchema, "query"), listCommunityPlacements);
router.post("/moderation/placements/:id", requireMarketplaceRole("moderator", "administrator"), validate(placementDecisionSchema), decideCommunityPlacement);
router.post("/moderation/account-cases", requireMarketplaceRole("administrator"), validate(accountCaseSchema), createAccountCase);
router.get("/moderation/cases", requireMarketplaceRole("moderator", "administrator"), validate(creatorDashboardQuerySchema, "query"), listMarketplaceCases);
router.post("/moderation/cases/:id", requireMarketplaceRole("moderator", "administrator"), validate(caseDecisionSchema), decideMarketplaceCase);
router.post("/moderation/appeals/:id", requireMarketplaceRole("moderator", "administrator"), validate(appealDecisionSchema), decideMarketplaceAppeal);
router.get("/item-types", listMarketplaceItemTypes);
router.get("/draft-options", listMarketplaceDraftOptions);
router.get("/products", validate(marketplaceProductQuerySchema, "query"), listMarketplaceProducts);
router.get("/products/:slug", getMarketplaceProduct);
router.get("/creator/profile", requireReader, requireMarketplaceAccess, getOwnedCreatorProfile);
router.post("/creator/profile", requireReader, requireMarketplaceAccess, requireVerifiedReader, validate(creatorOnboardingSchema), createOwnedCreatorProfile);
router.patch("/creator/profile", requireMarketplaceRole("creator"), validate(creatorProfileUpdateSchema), updateOwnedCreatorProfile);
router.get("/creator/dashboard", requireMarketplaceRole("creator"), validate(creatorDashboardQuerySchema, "query"), getCreatorDashboard);
router.get("/creator/provider-connections", requireMarketplaceRole("creator"), listOwnedProviderConnections);
router.put("/creator/provider-connections/:provider", requireMarketplaceRole("creator"), validate(providerConnectionSchema), connectOwnedProvider);
router.delete("/creator/provider-connections/:provider", requireMarketplaceRole("creator"), revokeOwnedProvider);
router.post("/creator/products", requireMarketplaceRole("creator"), validate(creatorDraftCreateSchema), createOwnedMarketplaceDraft);
router.get("/creator/products/:id/draft", requireMarketplaceRole("creator"), getOwnedMarketplaceDraft);
router.get("/creator/products/:id/releases", requireMarketplaceRole("creator"), listOwnedMarketplaceReleases);
router.post("/creator/products/:id/source-check", requireMarketplaceRole("creator"), validate(sourceCheckRequestSchema), enqueueOwnedSourceCheck);
router.put("/creator/products/:id/draft", requireMarketplaceRole("creator"), validate(creatorDraftUpdateSchema), updateOwnedMarketplaceDraft);
router.post("/creator/products/:id/lifecycle", requireMarketplaceRole("creator"), submissionLimit, validate(creatorListingLifecycleSchema), transitionOwnedMarketplaceListing);
router.get("/moderation/queue", requireMarketplaceRole("moderator", "administrator"), validate(moderationQueueQuerySchema, "query"), listMarketplaceModerationQueue);
router.get("/moderation/products/:id", requireMarketplaceRole("moderator", "administrator"), getMarketplaceModerationPreview);
router.post("/moderation/products/:id/notes", requireMarketplaceRole("moderator", "administrator"), validate(moderationNoteSchema), addMarketplaceModerationNote);
router.post("/moderation/products/:id/lifecycle", requireMarketplaceRole("moderator", "administrator"), validate(moderatedListingLifecycleSchema), transitionModeratedMarketplaceListing);
router.get("/favorites", requireReader, requireMarketplaceAccess, listMarketplaceFavorites);
router.get("/library", requireReader, requireMarketplaceAccess, validate(marketplaceLibraryQuerySchema, "query"), listMarketplaceLibrary);
router.put("/products/:slug/favorite", requireReader, requireMarketplaceAccess, addMarketplaceFavorite);
router.delete("/products/:slug/favorite", requireReader, requireMarketplaceAccess, removeMarketplaceFavorite);
router.get("/products/:slug/installation", requireReader, requireMarketplaceAccess, getMarketplaceInstallation);
router.post("/products/:slug/acquire", requireReader, requireMarketplaceAccess, acquireMarketplaceProduct);
export default router;
