import { Router } from "express";
import { addBookmark, changeReaderPassword, confirmReaderEmailVerification, getReaderLibrary, getReaderProfile, getReaderSession, loginReader, loginReaderWithGoogle, logoutReader, registerReader, removeBookmark, requestReaderEmailVerification, saveProgress, syncReaderLibrary } from "../controllers/readerController.js";
import { requireReader } from "../middleware/auth.js";
import { emailVerificationAttemptRateLimit, emailVerificationRequestRateLimit, loginRateLimit } from "../middleware/security.js";
import { validate } from "../middleware/validate.js";
import { emailVerificationConfirmSchema, googleCredentialSchema, readerCredentialsSchema, readerLibrarySyncSchema, readerPasswordChangeSchema, readerProgressSchema } from "../validation/schemas.js";

const router = Router();
router.post("/login", loginRateLimit, validate(readerCredentialsSchema), loginReader);
router.post("/register", loginRateLimit, validate(readerCredentialsSchema), registerReader);
router.post("/google", loginRateLimit, validate(googleCredentialSchema), loginReaderWithGoogle);
router.post("/logout", logoutReader);
router.get("/session", requireReader, getReaderSession);
router.get("/profile", requireReader, getReaderProfile);
router.post("/email-verification/request", requireReader, emailVerificationRequestRateLimit, requestReaderEmailVerification);
router.post("/email-verification/confirm", emailVerificationAttemptRateLimit, validate(emailVerificationConfirmSchema), confirmReaderEmailVerification);
router.put("/profile/password", requireReader, loginRateLimit, validate(readerPasswordChangeSchema), changeReaderPassword);
router.get("/library", requireReader, getReaderLibrary);
router.post("/library/sync", requireReader, validate(readerLibrarySyncSchema), syncReaderLibrary);
router.put("/articles/:slug/bookmark", requireReader, addBookmark);
router.delete("/articles/:slug/bookmark", requireReader, removeBookmark);
router.put("/articles/:slug/progress", requireReader, validate(readerProgressSchema), saveProgress);
export default router;
